In [8]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv("Student Stress Factors.csv")

In [11]:
df

,Timestamp,Kindly Rate your Sleep Quality üò¥,How many times a week do you suffer headaches ü§ï?,How would you rate you academic performance üë©‚Äçüéì?,how would you rate your study load?,How many times a week you practice extracurricular activities üéæ?,How would you rate your stress levels?
0,27/10/2023 21:54:15,3,1,3,4,2,3
1,28/10/2023 12:24:40,4,1,2,3,3,2
2,28/10/2023 12:24:51,2,1,2,1,4,4
3,28/10/2023 12:26:11,3,2,3,2,3,3
4,28/10/2023 12:26:45,2,3,1,5,5,3
5,28/10/2023 12:31:02,3,1,3,2,1,1
6,28/10/2023 12:34:45,3,5,1,4,3,5
7,28/10/2023 12:35:43,4,3,1,4,1,1
8,28/10/2023 12:36:07,2,1,4,4,5,1
9,28/10/2023 12:36:20,1,2,3,2,5,2
10,28/10/2023 12:37:22,2,3,5,5,2,4
11,28/10/2023 12:38:40,3,1,5,1,4,1
12,28/10/2023 12:39:43,2,3,3,4,4,3
13,28/10/2023 12:40:50,4,1,4,4,1,1
14,28/10/2023 12:41:12,4,1,3,2,5,2
15,28/10/2023 12:41:56,2,3,3,5,3,4
16,28/10/2023 12:48:22,3,1,3,3,3,4
17,28/10/2023 13:26:41,1,1,1,1,1,2
18,28/10/2023 13:28:47,2,1,3,1,2,3
19,28/10/2023 13:29:54,2,3,3,2,3,4
20,28/10/2023 13:30:57,3,4,2,2,1,2
21,28/10/2023 13:32:41,3,3,4,4,3,3
22,28/10/2023 13:33:15,2,1,2,3,2,2
23,28/10/2023 13:33:59,3,1,4,4,2,3
24,28/10/2023 13:41:28,5,1,4,2,1,1
25,28/10/2023 13:42:52,3,1,3,2,2,1
26,28/10/2023 13:44:07,5,1,5,1,5,5
27,28/10/2023 13:47:44,5,5,5,1,1,1
28,28/10/2023 13:52:22,2,3,3,1,1,2
29,28/10/2023 13:54:48,3,4,2,1,3,1
30,28/10/2023 13:57:20,5,1,3,5,5,5
31,28/10/2023 14:09:05,5,2,3,2,3,4
32,28/10/2023 14:27:19,5,5,4,5,2,5
33,28/10/2023 14:40:55,2,3,4,1,2,2
34,28/10/2023 14:58:39,4,1,5,4,5,2
35,28/10/2023 15:10:02,5,1,4,3,2,5
36,28/10/2023 15:10:43,4,1,1,2,4,5
37,28/10/2023 15:39:59,3,2,3,1,1,3
38,28/10/2023 16:16:13,3,4,4,5,3,1
39,28/10/2023 16:34:16,3,1,4,4,4,3
40,28/10/2023 16:55:49,4,4,3,2,2,2
41,28/10/2023 17:24:10,4,1,4,5,1,5
42,28/10/2023 17:26:18,4,2,3,3,5,4
43,28/10/2023 17:29:55,2,1,4,4,1,3
44,28/10/2023 17:31:52,5,1,4,5,4,5
45,28/10/2023 17:56:58,4,1,3,2,5,4
46,28/10/2023 22:33:48,2,1,4,4,1,4
47,28/10/2023 23:06:00,4,3,3,2,2,2
48,28/10/2023 23:45:09,3,3,4,4,4,3
49,29/10/2023 00:32:26,1,1,1,2,3,1
50,29/10/2023 11:40:20,5,1,5,1,3,3
51,31/10/2023 10:10:03,1,1,5,1,5,1
52,31/10/2023 20:49:11,3,2,3,2,5,2

In [12]:
df.isnull().sum()

Timestamp                                                           0
Kindly Rate your Sleep Quality üò¥                                    0
How many times a week do you suffer headaches ü§ï?                    0
How would you rate you academic performance üë©‚Äçüéì?                    0
how would you rate your study load?                                 0
How many times a week you practice extracurricular activities üéæ?    0
How would you rate your stress levels?                              0
dtype: int64

In [13]:
df.head()

,Timestamp,Kindly Rate your Sleep Quality üò¥,How many times a week do you suffer headaches ü§ï?,How would you rate you academic performance üë©‚Äçüéì?,how would you rate your study load?,How many times a week you practice extracurricular activities üéæ?,How would you rate your stress levels?
0,27/10/2023 21:54:15,3,1,3,4,2,3
1,28/10/2023 12:24:40,4,1,2,3,3,2
2,28/10/2023 12:24:51,2,1,2,1,4,4
3,28/10/2023 12:26:11,3,2,3,2,3,3
4,28/10/2023 12:26:45,2,3,1,5,5,3

In [14]:
df.tail()

,Timestamp,Kindly Rate your Sleep Quality üò¥,How many times a week do you suffer headaches ü§ï?,How would you rate you academic performance üë©‚Äçüéì?,how would you rate your study load?,How many times a week you practice extracurricular activities üéæ?,How would you rate your stress levels?
48,28/10/2023 23:45:09,3,3,4,4,4,3
49,29/10/2023 00:32:26,1,1,1,2,3,1
50,29/10/2023 11:40:20,5,1,5,1,3,3
51,31/10/2023 10:10:03,1,1,5,1,5,1
52,31/10/2023 20:49:11,3,2,3,2,5,2

In [15]:
df.columns

Index(['Timestamp', 'Kindly Rate your Sleep Quality üò¥',
       'How many times a week do you suffer headaches ü§ï?',
       'How would you rate you academic performance üë©‚Äçüéì?',
       'how would you rate your study load?',
       'How many times a week you practice extracurricular activities üéæ?',
       'How would you rate your stress levels?'],
      dtype='object')

In [16]:
df.shape

(53, 7)

In [33]:
type[df]

type[              Timestamp  Kindly Rate your Sleep Quality üò¥  \
0   27/10/2023 21:54:15                                 3
1   28/10/2023 12:24:40                                 4
2   28/10/2023 12:24:51                                 2
3   28/10/2023 12:26:11                                 3
4   28/10/2023 12:26:45                                 2
5   28/10/2023 12:31:02                                 3
6   28/10/2023 12:34:45                                 3
7   28/10/2023 12:35:43                                 4
8   28/10/2023 12:36:07                                 2
9   28/10/2023 12:36:20                                 1
10  28/10/2023 12:37:22                                 2
11  28/10/2023 12:38:40                                 3
12  28/10/2023 12:39:43                                 2
13  28/10/2023 12:40:50                                 4
14  28/10/2023 12:41:12                                 4
15  28/10/2023 12:41:56                                 2
16  28/10/2023 12:48:22                                 3
17  28/10/2023 13:26:41                                 1
18  28/10/2023 13:28:47                                 2
19  28/10/2023 13:29:54                                 2
20  28/10/2023 13:30:57                                 3
21  28/10/2023 13:32:41                                 3
22  28/10/2023 13:33:15                                 2
23  28/10/2023 13:33:59                                 3
24  28/10/2023 13:41:28                                 5
25  28/10/2023 13:42:52                                 3
26  28/10/2023 13:44:07                                 5
27  28/10/2023 13:47:44                                 5
28  28/10/2023 13:52:22                                 2
29  28/10/2023 13:54:48                                 3
30  28/10/2023 13:57:20                                 5
31  28/10/2023 14:09:05                                 5
32  28/10/2023 14:27:19                                 5
33  28/10/2023 14:40:55                                 2
34  28/10/2023 14:58:39                                 4
35  28/10/2023 15:10:02                                 5
36  28/10/2023 15:10:43                                 4
37  28/10/2023 15:39:59                                 3
38  28/10/2023 16:16:13                                 3
39  28/10/2023 16:34:16                                 3
40  28/10/2023 16:55:49                                 4
41  28/10/2023 17:24:10                                 4
42  28/10/2023 17:26:18                                 4
43  28/10/2023 17:29:55                                 2
44  28/10/2023 17:31:52                                 5
45  28/10/2023 17:56:58                                 4
46  28/10/2023 22:33:48                                 2
47  28/10/2023 23:06:00                                 4
48  28/10/2023 23:45:09                                 3
49  29/10/2023 00:32:26                                 1
50  29/10/2023 11:40:20                                 5
51  31/10/2023 10:10:03                                 1
52  31/10/2023 20:49:11                                 3

    How many times a week do you suffer headaches ü§ï?  \
0                                                  1
1                                                  1
2                                                  1
3                                                  2
4                                                  3
5                                                  1
6                                                  5
7                                                  3
8                                                  1
9                                                  2
10                                                 3
11                                                 1
12                                                 3
13                                                 1
14                                                 1
15                                                 3
16                                                 1
17                                                 1
18                                                 1
19                                                 3
20                                                 4
21                                                 3
22                                                 1
23                                                 1
24                                                 1
25                                                 1
26                                                 1
27                                                 5
28                                                 3
29                                                 4
30                                                 1
31                                                 2
32                                                 5
33                                                 3
34                                                 1
35                                                 1
36                                                 1
37                                                 2
38                                                 4
39                                                 1
40                                                 4
41                                                 1
42                                                 2
43                                                 1
44                                                 1
45                                                 1
46                                                 1
47                                                 3
48                                                 3
49                                                 1
50                                                 1
51                                                 1
52                                                 2

    How would you rate you academic performance üë©‚Äçüéì?  \
0                                                  3
1                                                  2
2                                                  2
3                                                  3
4                                                  1
5                                                  3
6                                                  1
7                                                  1
8                                                  4
9                                                  3
10                                                 5
11                                                 5
12                                                 3
13                                                 4
14                                                 3
15                                                 3
16                                                 3
17                                                 1
18                                                 3
19                                                 3
20                                                 2
21                                                 4
22                                                 2
23                                                 4
24                                                 4
25                                                 3
26                                                 5
27                                                 5
28                                                 3
29                                                 2
30                                                 3
31                                                 3
32                                                 4
33                                                 4
34                                                 5
35                                                 4
36                                                 1
37                                                 3
38                                                 4
39                                                 4
40                                                 3
41                                                 4
42                                                 3
43                                                 4
44                                                 4
45                                                 3
46                                                 4
47                                                 3
48                                                 4
49                                                 1
50                                                 5
51                                                 5
52                                                 3

    how would you rate your study load?  \
0                                     4
1                                     3
2                                     1
3                                     2
4                                     5
5                                     2
6                                     4
7                                     4
8                                     4
9                                     2
10                                    5
11                                    1
12                                    4
13                                    4
14                                    2
15                                    5
16                                    3
17                                    1
18                                    1
19                                    2
20                                    2
21                                    4
22                                    3
23                                    4
24                                    2
25                                    2
26                                    1
27                                    1
28                                    1
29                                    1
30                                    5
31                                    2
32                                    5
33                                    1
34                                    4
35                                    3
36                                    2
37                                    1
38                                    5
39                                    4
40                                    2
41                                    5
42                                    3
43                                    4
44                                    5
45                                    2
46                                    4
47                                    2
48                                    4
49                                    2
50                                    1
51                                    1
52                                    2

    How many times a week you practice extracurricular activities üéæ?  \
0                                                   2
1                                                   3
2                                                   4
3                                                   3
4                                                   5
5                                                   1
6                                                   3
7                                                   1
8                                                   5
9                                                   5
10                                                  2
11                                                  4
12                                                  4
13                                                  1
14                                                  5
15                                                  3
16                                                  3
17                                                  1
18                                                  2
19                                                  3
20                                                  1
21                                                  3
22                                                  2
23                                                  2
24                                                  1
25                                                  2
26                                                  5
27                                                  1
28                                                  1
29                                                  3
30                                                  5
31                                                  3
32                                                  2
33                                                  2
34                                                  5
35                                                  2
36                                                  4
37                                                  1
38                                                  3
39                                                  4
40                                                  2
41                                                  1
42                                                  5
43                                                  1
44                                                  4
45                                                  5
46                                                  1
47                                                  2
48                                                  4
49                                                  3
50                                                  3
51                                                  5
52                                                  5

    How would you rate your stress levels?
0                                        3
1                                        2
2                                        4
3                                        3
4                                        3
5                                        1
6                                        5
7                                        1
8                                        1
9                                        2
10                                       4
11                                       1
12                                       3
13                                       1
14                                       2
15                                       4
16                                       4
17                                       2
18                                       3
19                                       4
20                                       2
21                                       3
22                                       2
23                                       3
24                                       1
25                                       1
26                                       5
27                                       1
28                                       2
29                                       1
30                                       5
31                                       4
32                                       5
33                                       2
34                                       2
35                                       5
36                                       5
37                                       3
38                                       1
39                                       3
40                                       2
41                                       5
42                                       4
43                                       3
44                                       5
45                                       4
46                                       4
47                                       2
48                                       3
49                                       1
50                                       3
51                                       1
52                                       2  ]

In [19]:
df.loc[0]

Timestamp                                                           27/10/2023 21:54:15
Kindly Rate your Sleep Quality üò¥                                                      3
How many times a week do you suffer headaches ü§ï?                                      1
How would you rate you academic performance üë©‚Äçüéì?                                      3
how would you rate your study load?                                                   4
How many times a week you practice extracurricular activities üéæ?                      2
How would you rate your stress levels?                                                3
Name: 0, dtype: object

In [20]:
x=df.iloc[:,:-1]

In [30]:
y=df.iloc[:,:3]

In [27]:
x

,Timestamp,Kindly Rate your Sleep Quality üò¥,How many times a week do you suffer headaches ü§ï?,How would you rate you academic performance üë©‚Äçüéì?,how would you rate your study load?,How many times a week you practice extracurricular activities üéæ?
0,27/10/2023 21:54:15,3,1,3,4,2
1,28/10/2023 12:24:40,4,1,2,3,3
2,28/10/2023 12:24:51,2,1,2,1,4
3,28/10/2023 12:26:11,3,2,3,2,3
4,28/10/2023 12:26:45,2,3,1,5,5
5,28/10/2023 12:31:02,3,1,3,2,1
6,28/10/2023 12:34:45,3,5,1,4,3
7,28/10/2023 12:35:43,4,3,1,4,1
8,28/10/2023 12:36:07,2,1,4,4,5
9,28/10/2023 12:36:20,1,2,3,2,5
10,28/10/2023 12:37:22,2,3,5,5,2
11,28/10/2023 12:38:40,3,1,5,1,4
12,28/10/2023 12:39:43,2,3,3,4,4
13,28/10/2023 12:40:50,4,1,4,4,1
14,28/10/2023 12:41:12,4,1,3,2,5
15,28/10/2023 12:41:56,2,3,3,5,3
16,28/10/2023 12:48:22,3,1,3,3,3
17,28/10/2023 13:26:41,1,1,1,1,1
18,28/10/2023 13:28:47,2,1,3,1,2
19,28/10/2023 13:29:54,2,3,3,2,3
20,28/10/2023 13:30:57,3,4,2,2,1
21,28/10/2023 13:32:41,3,3,4,4,3
22,28/10/2023 13:33:15,2,1,2,3,2
23,28/10/2023 13:33:59,3,1,4,4,2
24,28/10/2023 13:41:28,5,1,4,2,1
25,28/10/2023 13:42:52,3,1,3,2,2
26,28/10/2023 13:44:07,5,1,5,1,5
27,28/10/2023 13:47:44,5,5,5,1,1
28,28/10/2023 13:52:22,2,3,3,1,1
29,28/10/2023 13:54:48,3,4,2,1,3
30,28/10/2023 13:57:20,5,1,3,5,5
31,28/10/2023 14:09:05,5,2,3,2,3
32,28/10/2023 14:27:19,5,5,4,5,2
33,28/10/2023 14:40:55,2,3,4,1,2
34,28/10/2023 14:58:39,4,1,5,4,5
35,28/10/2023 15:10:02,5,1,4,3,2
36,28/10/2023 15:10:43,4,1,1,2,4
37,28/10/2023 15:39:59,3,2,3,1,1
38,28/10/2023 16:16:13,3,4,4,5,3
39,28/10/2023 16:34:16,3,1,4,4,4
40,28/10/2023 16:55:49,4,4,3,2,2
41,28/10/2023 17:24:10,4,1,4,5,1
42,28/10/2023 17:26:18,4,2,3,3,5
43,28/10/2023 17:29:55,2,1,4,4,1
44,28/10/2023 17:31:52,5,1,4,5,4
45,28/10/2023 17:56:58,4,1,3,2,5
46,28/10/2023 22:33:48,2,1,4,4,1
47,28/10/2023 23:06:00,4,3,3,2,2
48,28/10/2023 23:45:09,3,3,4,4,4
49,29/10/2023 00:32:26,1,1,1,2,3
50,29/10/2023 11:40:20,5,1,5,1,3
51,31/10/2023 10:10:03,1,1,5,1,5
52,31/10/2023 20:49:11,3,2,3,2,5

In [31]:
y

,Timestamp,Kindly Rate your Sleep Quality üò¥,How many times a week do you suffer headaches ü§ï?
0,27/10/2023 21:54:15,3,1
1,28/10/2023 12:24:40,4,1
2,28/10/2023 12:24:51,2,1
3,28/10/2023 12:26:11,3,2
4,28/10/2023 12:26:45,2,3
5,28/10/2023 12:31:02,3,1
6,28/10/2023 12:34:45,3,5
7,28/10/2023 12:35:43,4,3
8,28/10/2023 12:36:07,2,1
9,28/10/2023 12:36:20,1,2
10,28/10/2023 12:37:22,2,3
11,28/10/2023 12:38:40,3,1
12,28/10/2023 12:39:43,2,3
13,28/10/2023 12:40:50,4,1
14,28/10/2023 12:41:12,4,1
15,28/10/2023 12:41:56,2,3
16,28/10/2023 12:48:22,3,1
17,28/10/2023 13:26:41,1,1
18,28/10/2023 13:28:47,2,1
19,28/10/2023 13:29:54,2,3
20,28/10/2023 13:30:57,3,4
21,28/10/2023 13:32:41,3,3
22,28/10/2023 13:33:15,2,1
23,28/10/2023 13:33:59,3,1
24,28/10/2023 13:41:28,5,1
25,28/10/2023 13:42:52,3,1
26,28/10/2023 13:44:07,5,1
27,28/10/2023 13:47:44,5,5
28,28/10/2023 13:52:22,2,3
29,28/10/2023 13:54:48,3,4
30,28/10/2023 13:57:20,5,1
31,28/10/2023 14:09:05,5,2
32,28/10/2023 14:27:19,5,5
33,28/10/2023 14:40:55,2,3
34,28/10/2023 14:58:39,4,1
35,28/10/2023 15:10:02,5,1
36,28/10/2023 15:10:43,4,1
37,28/10/2023 15:39:59,3,2
38,28/10/2023 16:16:13,3,4
39,28/10/2023 16:34:16,3,1
40,28/10/2023 16:55:49,4,4
41,28/10/2023 17:24:10,4,1
42,28/10/2023 17:26:18,4,2
43,28/10/2023 17:29:55,2,1
44,28/10/2023 17:31:52,5,1
45,28/10/2023 17:56:58,4,1
46,28/10/2023 22:33:48,2,1
47,28/10/2023 23:06:00,4,3
48,28/10/2023 23:45:09,3,3
49,29/10/2023 00:32:26,1,1
50,29/10/2023 11:40:20,5,1
51,31/10/2023 10:10:03,1,1
52,31/10/2023 20:49:11,3,2